[build-system]
requires = ["aiofiles == 0.7.0", "fastapi == 0.65.1", "jinja2 == 3.0.1", "requests == 2.25.1", "setuptools >= 40.6.0", "uvicorn[standard]", "wheel"]
build-backend = "setuptools.build_meta"
