"""add budget

Revision ID: 45c9f6797fea
Revises: bf2c79c82fb0
Create Date: 2021-06-23 20:29:06.074604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c9f6797fea'
down_revision = 'bf2c79c82fb0'
branch_labels = None
depends_on = None


def upgrade():
	op.create_table('budget',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('start_date', sa.Date(), nullable=True),
		sa.Column('end_date', sa.Date(), nullable=True),
		sa.Column('type', sa.Enum('owner', name='accountpermissiontype'), nullable=True),
		sa.Column('version', sa.Integer(), nullable=False),
		sa.PrimaryKeyConstraint('id'),
		sqlite_autoincrement=True
	)
	op.create_index(op.f('ix_budget_id'), 'budget', ['id'], unique=False)
	op.create_table('budget_history',
		sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
		sa.Column('start_date', sa.Date(), autoincrement=False, nullable=True),
		sa.Column('end_date', sa.Date(), autoincrement=False, nullable=True),
		sa.Column('type', sa.Enum('owner', name='accountpermissiontype'), autoincrement=False, nullable=True),
		sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
		sa.Column('changed', sa.DateTime(), nullable=True),
		sa.PrimaryKeyConstraint('id', 'version')
	)
	op.create_index(op.f('ix_budget_history_id'), 'budget_history', ['id'], unique=False)
	op.create_table('budget_entry',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('budget_id', sa.Integer(), nullable=True),
		sa.Column('name', sa.String(), nullable=True),
		sa.Column('amount', sa.Float(), nullable=True),
		sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], ),
		sa.PrimaryKeyConstraint('id')
	)
	op.create_index(op.f('ix_budget_entry_id'), 'budget_entry', ['id'], unique=False)
	op.create_table('budget_permission',
		sa.Column('budget_id', sa.Integer(), nullable=False),
		sa.Column('user_id', sa.Integer(), nullable=False),
		sa.Column('type', sa.Enum('owner', name='budgetpermissiontype'), nullable=True),
		sa.ForeignKeyConstraint(['budget_id'], ['budget.id'], ),
		sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
		sa.PrimaryKeyConstraint('budget_id', 'user_id')
	)
	with op.batch_alter_table("transaction") as batch_op:
		batch_op.add_column(sa.Column('budget_entry', sa.Integer(), nullable=True))
		batch_op.create_foreign_key('fk_budget_entry_id', 'budget_entry', ['budget_entry'], ['id'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_budget_entry_id', 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'budget_entry')
    op.alter_column('import_job', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_reconciliation_id'), table_name='reconciliation')
    op.drop_table('reconciliation')
    op.drop_table('budget_permission')
    op.drop_index(op.f('ix_budget_entry_id'), table_name='budget_entry')
    op.drop_table('budget_entry')
    op.drop_index(op.f('ix_budget_history_id'), table_name='budget_history')
    op.drop_table('budget_history')
    op.drop_index(op.f('ix_budget_id'), table_name='budget')
    op.drop_table('budget')
    # ### end Alembic commands ###
